### ISSUE TITLE
one case does not covered in this library

### ISSUE THREAD

**Issue by engshorouq** [skeggse/isemail#210]
depend on this article  https://en.wikipedia.org/wiki/Email_address
the case it :
" "@example.org (space between the quotes) accepted
but in this library does not accept this case

**Comment by skeggse** [comment]
This is actually supported, I believe - it's just flagged as deprecated in the output:
```js
> Isemail.validate('" "@g.com', {errorLevel: true})
35 // deprecatedQTEXT
```
